### ISSUE TITLE
ci_manifest.sh failed to upload MANIFEST.json for merge_pr_10605

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#10672]
https://github.com/w3c/web-platform-tests/pull/10605 landed as commit 8e66eb476c019bc90ca345faf2c7178dab0c0837 and was tagged as merge_pr_10605 in this Travis build:
https://travis-ci.org/w3c/web-platform-tests/builds/371536851.

However, https://travis-ci.org/w3c/web-platform-tests/jobs/371536852 failed, ending like this:
```
Current tag is: merge_pr_10605
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://uploads.github.com/repos/w3c/web-platform-tests/releases/10734070/assets?name=MANIFEST-8e66eb476c019bc90ca345faf2c7178dab0c0837.json.gz: 502 - Error uploading asset (Octokit::BadGateway)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.0/lib/faraday/connection.rb:175:in `post'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:138:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:119:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:109:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:109:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

As a result, no MANIFEST.json was uploaded. Compare to previously tagged commit:
https://github.com/w3c/web-platform-tests/releases/tag/merge_pr_10497
https://github.com/w3c/web-platform-tests/releases/tag/merge_pr_10605

**Comment by foolip** [comment]
@jgraham seems like this was a network problem.

https://docs.travis-ci.com/user/common-build-problems/ mentions `travis_retry`, but: "Note that travis_retry only works within the script step. It will not work in other steps, like deploy."

And we are using the deploy step:
```yaml
    - os: linux
      python: "2.7"
      env:
        - JOB=manifest_upload SCRIPT=tools/ci/ci_manifest.sh
        - secure: "FrlMkMZiwggnhJbLiLxZ4imtXxuzFNozty94g1mneMPEVLrnyhb6c/g2SwN37KKU0WSDlGTz26IYnFvo1ftfSOx+sjRz0HqwW7JnrXULKYo7jiPttIcmeJxlSVeW9yS4blbLaBakytHjSnsf+za7bAaf1aS7RRAtAINgifA6Chg="
      deploy:
        provider: releases
        api_key:
          secure: "EljDx50oNpDLs7rzwIv+z1PxIgB5KMnx1W0OQkpNvltR0rBW9g/aQaE+Z/c8M/sPqN1bkvKPybKzGKjb6j9Dw3/EJhah4SskH78r3yMAe2DU/ngxqqjjfXcCc2t5MKxzHAILTAxqScPj2z+lG1jeK1Z+K5hTbSP9lk+AvS0D16w="
        file: $WPT_MANIFEST_FILE.gz
        skip_cleanup: true
```
