### ISSUE TITLE
[css-text] missing font in css-text i18n tests

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#17995]
The `wpt/css/css-text/i18n/css3-text-line-break-baspglwj-*.html` tests include:
```css
@font-face {
    font-family: 'csstest_ascii';
    src: url('support/csstest-ascii-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
	}
#breakable { font-family: csstest_ascii; 
```

However, that font is missing. The tests happen to work on typical systems because the default font typically has metrics that play well with this test, but it is not reliable.

One way to fix this would be to add the font to the repository.

However, I think a better way to fix this would be to remove the request for any particular font, and instead, use the generic `monospace` font family. We could then size the element width in `ch` units, to ensure that the line has the right length to trigger the break-point where expected (e.g. `50ch`). Given that the text has no dependency on what the glyphs actually look like, this simplification seems like a better approach.

I'm happy to do the fix if we agree, but I'd like confirmation first. @r12a @xfq @fantasai
