### ISSUE TITLE
`wpt test-jobs` can silently fail on Azure Pipelines

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#26448]
Examples:
* https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=57167&view=logs&j=3a8a797a-cea8-5b38-08dd-c96687b91c17&t=4ef2e921-1fd4-56ed-4613-9c718b9f4b92
* https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=57172&view=logs&jobId=3a8a797a-cea8-5b38-08dd-c96687b91c17&j=3a8a797a-cea8-5b38-08dd-c96687b91c17&t=4ef2e921-1fd4-56ed-4613-9c718b9f4b92

The problem is that the script just pipes the `wpt` command into a read:

```
- job: decision
  displayName: './wpt test-jobs'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: tools/ci/azure/checkout.yml
  - script: |
      ./wpt test-jobs | while read job; do
        echo "$job"
        echo "##vso[task.setvariable variable=$job;isOutput=true]true";
      done
    name: test_jobs
    displayName: 'Run ./wpt test-jobs'
```

If `wpt test-jobs` fails here, we will never notice and we'll just schedule the default jobs only.

Impact here is hard to determine - I noticed a failure on one PR when the job I expected wasn't scheduled, but of course this could have been failing for essentially forever on certain PRs and we wouldn't notice in general.

I think we can just add `set -o pipefail` to the script here. Maybe `set -e` too for good measure.
