### ISSUE TITLE
Add API to force classic scrollbars

### ISSUE THREAD

**Issue by Loirooriol** [web-platform-tests/wpt#36422]
CSS allows UAs to use either [classic scrollbars](https://w3c.github.io/csswg-drafts/css-overflow-3/#classic-scrollbars) or [overlay scrollbars](https://w3c.github.io/csswg-drafts/css-overflow-3/#overlay-scrollbars).

Classic scrollbars are much more error-prone since they affect layout. However, writing tests may not be useful because they can seem to pass on a buggy UA just because it decides to use overlay scrollbars instead.

So it would be useful to have some way of forcing the UA to use classic scrollbars in these tests.

Note that browsers are already capable of that: Firefox uses classic scrollbars with the pref `ui.useOverlayScrollbars=0`, and Blink/WebKit seem to use classic scrollbars with this CSS hack:

```css
::-webkit-scrollbar { background-color: #eff0f1; width: 12px; height: 12px; }
::-webkit-scrollbar-thumb { background: #898c8d; }
```

So it would be a matter of exposing this behavior to WPT tests.
