### ISSUE TITLE
vhal should not be applied to horizontal text

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#42275]
In the following test ref files:
* https://github.com/web-platform-tests/wpt/blob/master/css/css-text/text-spacing-trim/reference/text-spacing-trim-001-ref.html
* https://github.com/web-platform-tests/wpt/blob/master/css/css-text/text-spacing-trim/reference/text-spacing-trim-dot-001-ref.html
* https://github.com/web-platform-tests/wpt/blob/master/css/css-text/text-spacing-trim/reference/text-spacing-trim-colon-001-ref.html

The `vhal` feature is applied all the time, but I believe it should only be applied in the vertical variant of the test. In other words, unless I am missing something, instead of
```css
halt {
  font-feature-settings: 'halt' 1, 'vhal' 1;
}
```
we should have
```css
halt {
  font-feature-settings: 'halt' 1;
}
.vrl halt {
  font-feature-settings: 'halt' 1, 'vhal' 1;
}
```

cc: @kojiishi @fantasai
